// Code generated by MockGen. DO NOT EDIT.
// Source: report.go

// Package report is a generated GoMock package.
package report

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockReporter) Report(ctx context.Context, r io.Reader, info ReportInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report", ctx, r, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockReporterMockRecorder) Report(ctx, r, info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockReporter)(nil).Report), ctx, r, info)
}

// MockBatchReporter is a mock of BatchReporter interface.
type MockBatchReporter struct {
	ctrl     *gomock.Controller
	recorder *MockBatchReporterMockRecorder
}

// MockBatchReporterMockRecorder is the mock recorder for MockBatchReporter.
type MockBatchReporterMockRecorder struct {
	mock *MockBatchReporter
}

// NewMockBatchReporter creates a new mock instance.
func NewMockBatchReporter(ctrl *gomock.Controller) *MockBatchReporter {
	mock := &MockBatchReporter{ctrl: ctrl}
	mock.recorder = &MockBatchReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchReporter) EXPECT() *MockBatchReporterMockRecorder {
	return m.recorder
}

// ReportBatch mocks base method.
func (m *MockBatchReporter) ReportBatch(ctx context.Context, items []ReportItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportBatch", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportBatch indicates an expected call of ReportBatch.
func (mr *MockBatchReporterMockRecorder) ReportBatch(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportBatch", reflect.TypeOf((*MockBatchReporter)(nil).ReportBatch), ctx, items)
}
